name: Upload Smoke Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: windows-latest
    env:
      PRESIGN_API_BASE: ${{ secrets.PRESIGN_API_BASE }}
      PRESIGN_API_KEY:  ${{ secrets.PRESIGN_API_KEY }}
      PRESIGN_HMAC_SECRET: ${{ secrets.PRESIGN_HMAC_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show env
        shell: pwsh
        run: $PSVersionTable

      - name: Run presign smoke test
        shell: pwsh
        run: .\scripts\presign-smoke.ps1
