name: CI (PR)
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  smoke:
    name: Presign + upload (PowerShell)
    runs-on: windows-latest
    timeout-minutes: 10
    concurrency:
      group: lifebook-ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run smoke script
        shell: pwsh
        env:
          PRESIGN_API_BASE: ${{ secrets.PRESIGN_API_BASE }}
          PRESIGN_API_KEY: ${{ secrets.PRESIGN_API_KEY }}
          PRESIGN_HMAC_SECRET: ${{ secrets.PRESIGN_HMAC_SECRET }}
          CF_BASE_URL: ${{ secrets.CF_BASE_URL }}
        run: |
          Set-ExecutionPolicy -Scope Process Bypass -Force
          .\.github\workflows\scripts\smoke.ps1

