name: e2e-pr-smoke (manual)
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or SHA to test
        required: true
        default: main

permissions:
  id-token: write
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      PRESIGN_API_BASE:  ${{ secrets.PRESIGN_API_BASE }}
      PRESIGN_METHOD:    ${{ secrets.PRESIGN_METHOD }}
      PRESIGN_PATH:      ${{ secrets.PRESIGN_PATH }}
      PRESIGN_API_KEY:   ${{ secrets.PRESIGN_API_KEY }}
      PRESIGN_HMAC_SECRET: ${{ secrets.PRESIGN_HMAC_SECRET }}
      CF_BASE_URL:       ${{ secrets.CF_BASE_URL }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Configure AWS creds via OIDC
        if: ${{ env.AWS_OIDC_ROLE_ARN != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate required secrets
        shell: bash
        run: |
          set -euo pipefail
          : "${PRESIGN_API_BASE:?}"; : "${PRESIGN_API_KEY:?}"; : "${PRESIGN_HMAC_SECRET:?}"; : "${CF_BASE_URL:?}"
          : "${PRESIGN_PATH:?}"

      - name: Presign → PUT → GET via CloudFront
        shell: bash
        run: |
          set -euo pipefail
          TS=$(date +%s)
          BODY='{"key":"sources/smoke/pr-'"$GITHUB_RUN_ID"'.txt","contentType":"text/plain","contentDisposition":"inline"}'

          # HMAC(ts.body) with hex OR base64 key
          SIG=$(python3 -c "import sys,hmac,hashlib,base64,binascii; ts,body,key=sys.argv[1:4]; \
try: k=binascii.unhexlify(key) \
except binascii.Error: k=base64.b64decode(key, validate=True) \
print(hmac.new(k, f'{ts}.{body}'.encode(), hashlib.sha256).hexdigest())" "$TS" "$BODY" "$PRESIGN_HMAC_SECRET")

          URL_BASE="${PRESIGN_API_BASE%/}${PRESIGN_PATH}"
          code=$(curl --silent --show-error --fail-with-body \
            -o /tmp/presign.json -w '%{http_code}' \
            -X "${PRESIGN_METHOD:-POST}" "$URL_BASE" \
            -H "x-api-key: $PRESIGN_API_KEY" \
            -H "x-timestamp: $TS" \
            -H "x-signature: $SIG" \
            -H "content-type: application/json" \
            -d "$BODY" || true)

          echo "presign HTTP=$code url=$URL_BASE"
          sed -e 's/[A-Za-z0-9_]\{24,\}/[redacted]/g' /tmp/presign.json || true
          test "$code" = "200"

          URL=$(jq -r .url /tmp/presign.json)
          echo "Presign URL obtained: ${URL%%\?*}"

          echo "hello from e2e smoke $GITHUB_RUN_ID" > /tmp/smoke.txt
          curl -sfS -X PUT -T /tmp/smoke.txt "$URL" -H "x-amz-server-side-encryption: AES256"

          KEY=$(python3 -c 'import sys; from urllib.parse import urlparse; p=urlparse(sys.argv[1]).path; print(p.split("/",3)[-1])' "$URL")
          GET_URL="${CF_BASE_URL%/}/$KEY"
          echo "Verifying via CloudFront: $GET_URL"
          curl -sfS "$GET_URL" | tee /tmp/fetched.txt
          grep -q "hello from e2e smoke" /tmp/fetched.txt
