name: OIDC debug
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/oidc-debug.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no effect; keeps logs tidy)
        uses: actions/checkout@v4

      - name: Show OIDC token aud/sub
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const body = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString('utf8'));
            core.info(`OIDC aud: ${JSON.stringify(body.aud)}`);
            core.info(`OIDC sub: ${body.sub}`);

